# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - frontend-finance-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
volumes:
  frontend-finance-db:
    driver: local
